### ISSUE TITLE
Add versioning for the validator

### ISSUE THREAD

**Issue by Ortham** [loot/metadata-validator#1]
The validator will print the version of the LOOT API it's using, but it should also have its own version number. I tagged a commit as `1.0.0` in order to get CI builds passing, but the validator version should probably be `0.10.4` to better match the API. When proper versioning of the validator is added, the `1.0.0` tag should be replaced accordingly.

**Comment by Freso** [comment]
Should this live in v0.8, v0.10, etc. branches like the masterlists?

**Comment by Ortham** [comment]
I don't think that's necessary, since tagged releases will have binaries available, and there's no need to be able to point to the latest version in a release series.

**Comment by Ortham** [comment]
Done in 49292546a776641ba1cfbe352f2acb150fb96af2.
